---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: k8s-at-home
spec:
  interval: 30m
  url: https://k8s-at-home.com/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openebs
spec:
  interval: 30m
  url: https://openebs.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openebs-nfs
spec:
  interval: 30m
  url: https://openebs.github.io/dynamic-nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 30m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: redhat-cop
spec:
  interval: 30m
  url: https://redhat-cop.github.io/helm-charts