apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      version: '9.3.0'
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    image:
      repository: jellyfin/jellyfin
      tag: 10.8.0-alpha5
      pullPolicy: IfNotPresent
    env: # https://jellyfin.org/docs/general/administration/configuration.html
      TZ: Europe/Amsterdam
    service:
      main:
        enabled: true
        primary: true
        ports:
          http:
            enabled: true
            primary: true
            port: 80
            targetPort: 8096
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
        mountPath: /config
        storageClass: harddrive-disk
        retain: true
      cache: # Cache does NOT contain temporary transcoding data.
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
        mountPath: /cache
        storageClass: harddrive-disk
        retain: true
      media:
        enabled: true
        type: pvc
        existingClaim: media-storage
        mountPath: /media
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 100  # users
      supplementalGroups:
      - 44
      - 109
    resources:
      requests:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        # gpu.intel.com/i915: 1
        cpu: 200m
        memory: 256Mi
      limits:
        # Hardware acceleration using an Intel iGPU w/ QuickSync and
        # using intel-gpu-plugin (https://github.com/intel/intel-device-plugins-for-kubernetes)
        # gpu.intel.com/i915: 1
        memory: 4096Mi
