apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: openebs-kernel-nfs
  resources:
    requests:
      storage: 256Gi
