---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: harddrive-nfs-unsafe
  resources:
    requests:
      storage: 4Ti
