apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
spec:
  releaseName: radarr
  chart:
    spec:
      chart: radarr
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    env:
      TZ: Europe/Amsterdam
    service:
      main:
        ports:
          http:
            port: 80
            targetPort: 7878
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: false
      media:
        enabled: false
        mountPath: /media
      cache:
        enabled: false
        mountPath: /cache
    metrics:
      enabled: false
