apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keepalived-operator
spec:
  releaseName: keepalived-operator
  chart:
    spec:
      chart: keepalived-operator
      sourceRef:
        kind: HelmRepository
        name: redhat-cop
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
