apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        keepalived-operator.redhat-cop.io/keepalivedgroup: networking/keepalivedgroup
      externalIPs: 
        - 10.9.8.200