apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    ingressClass:
      enabled: false
      # isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: true
    ports:
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
        # redirectTo: websecure
      websecure:
        port: 8443
        expose: true
        exposedPort: 443
        protocol: TCP
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        keepalived-operator.redhat-cop.io/keepalivedgroup: networking/keepalivedgroup
      externalIPs: 
        - 10.9.8.200
    ingressRoute:
      dashboard:
        enabled: false
    logs:
      # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
      general:
        # By default, the logs use a text format (common), but you can
        # also ask for the json format in the format option
        # format: json
        # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
        level: ERROR
      access:
        # To enable access logs
        enabled: true