apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - namespace.yaml
  - openebs.yaml
  - openebs-nfs.yaml
  # - CStorPoolClusters.yaml
  # - StorageClasses.yaml