kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: harddrive-disk
  labels:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  cas-type: cstor
  cstorPoolCluster: harddrive-disk-pool # cstorPoolCluster should have the name of the CSPC 
  replicaCount: "3" # replicaCount should be <= no. of CSPI created in the selected CSPC
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: harddrive-disk-unsafe
  labels:
    "storageclass.kubernetes.io/is-default-class": "false"
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  cas-type: cstor
  cstorPoolCluster: harddrive-disk-pool-unsafe # cstorPoolCluster should have the name of the CSPC 
  replicaCount: "1" # replicaCount should be <= no. of CSPI created in the selected CSPC
